version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: urutte-postgres
    restart: always
    environment:
      POSTGRES_DB: urutte_prod
      POSTGRES_USER: urutte_user
      POSTGRES_PASSWORD: urutte_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urutte-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urutte_user -d urutte_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: urutte-backend-prod
    container_name: urutte-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urutte_prod
      SPRING_DATASOURCE_USERNAME: urutte_user
      SPRING_DATASOURCE_PASSWORD: urutte_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: 1051698753493-sn49e56i0qt9fqh47kd3dpcv11lk03v3.apps.googleusercontent.com
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: 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
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: https://urutte.com/login/oauth2/code/google
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: profile,email
      APP_OAUTH2_REDIRECT_URI: https://urutte.com/login?token={token}
      APP_FRONTEND_URL: https://urutte.com
      APP_CORS_ALLOWED_ORIGINS: https://urutte.com,https://www.urutte.com,http://urutte.com
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      UPLOAD_DIR: /app/uploads
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
    expose:
      - "8080"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - urutte-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: urutte-frontend-prod
    container_name: urutte-frontend
    restart: always
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - urutte-network

  nginx:
    image: nginx:alpine
    container_name: urutte-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - urutte-network

  certbot:
    image: certbot/certbot
    container_name: urutte-certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@urutte.com --agree-tos --no-eff-email -d urutte.com -d www.urutte.com

volumes:
  postgres_data:
  backend_uploads:
  certbot_www:
  certbot_conf:

networks:
  urutte-network:
    driver: bridge