services:
  postgres:
    image: postgres:15
    container_name: urutte-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: urutte_prod
      POSTGRES_USER: urutte_user
      POSTGRES_PASSWORD: urutte_pass
    ports:
      - "5432:5432"
    volumes:
      # Preserve database data
      - postgres_data_prod:/var/lib/postgresql/data
      # Backup directory
      - ./backups:/backups
    networks:
      - urutte-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urutte_user -d urutte_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: urutte-backend-prod
    container_name: urutte-backend-prod
    restart: unless-stopped
    env_file:
      - config/production.env
    ports:
      - "8080:8080"
    volumes:
      # Preserve upload data
      - backend_uploads_prod:/app/uploads
      # Logs directory
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - urutte-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: urutte-frontend-prod
    container_name: urutte-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - urutte-network

  nginx:
    image: nginx:alpine
    container_name: urutte-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Preserve nginx logs
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - urutte-network

volumes:
  # Named volumes to preserve data across deployments
  postgres_data_prod:
    driver: local
  backend_uploads_prod:
    driver: local

networks:
  urutte-network:
    driver: bridge